version: '3'

services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=studantdb
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pedro@yahoo.com.br
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2019!
    ports:
      - "16543:80"
    depends_on:
      - postgresqldb
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge